# Generated by Django 4.2 on 2023-04-28 11:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('alternate_phonenumber', models.IntegerField(blank=True)),
                ('addressline_one', models.CharField(max_length=100)),
                ('addressline_two', models.CharField(blank=True, max_length=100)),
                ('country_or_city', models.TextField(default=True, max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('company_name', models.TextField(blank=True, max_length=100)),
                ('company_type', models.TextField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_table',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
